# Global constants
skeleton:
  year: { start: 2000, end: 2024 }
  age: { start: 0, end: 100 }
  sex: { Male: 'Male', Female: 'Female' }
  regions: [
      'AT',
      #'AU', only 5 age groups
      'BE',
      'BG',
      #'CA', only 4 age groups
      'CH',
      'CL',
      'CZ',
      'DE',
      'DK',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB-EAW',
      'GB-NIR',
      'GB-SCT',
      'GR',
      'HR',
      'HU',
      'IL', # only 8 age groups
      'IS',
      'IT',
      'JP',
      #'KR', only 5 age groups
      'LT',
      'LU',
      'LV',
      'NL',
      'NO',
      #'NZ', only 3 age groups
      'PL',
      'PT',
      #'RU',
      'SE',
      'SI',
      'SK',
      'TW',
      'US',
    ]
visualclusters:
  {
    'A First wave peak': ['BE', 'GB-EAW', 'IT', 'SI', 'ES', 'SE', 'CH', 'LU', 'GB-SCT'],
    'B Second wave peak': ['BG', 'HR', 'CZ', 'EE', 'GR', 'HU', 'LV', 'LT', 'PL', 'SK', 'US', 'CL'],
    'C Late peak': ['DK', 'FI', 'IS', 'DE', 'NO', 'TW', 'JP'],
    'D Prolonged depression': ['AT', 'FR', 'IL', 'NL', 'GB-NIR', 'PT']
  }
clustermethod: 'cluster_fixed'
clusternames:
  A: 'A First wave peak'
  B: 'B Second wave peak'
  C: 'C Late peak'
  D: 'D Prolonged depression'
# select exposures to use by default for each country
exposureselection:
  {
    'hmd': [
      'BE', 'CH', 'DK', 'EE', 'FI', 'JP', 'LT', 'LV', 'NO', 'PT', 'SE', 'SK',
      'GB-EAW', 'GB-NIR', 'GB-SCT'],
    'wpp24': [
      'BG',  'CZ', 'DE', 'ES',  'FR', 'GR', 'AT', 'CL', 'HR',
      'TW', 'US', 'HU', 'IL', 'IS', 'IT',  'LU',  'NL',  'PL', 'SI'
    ],
    'wpp22': []
  }
# select countries for which to use rate bias correction model
ratebiascorrection:
  {
    # for cases where correction makes estimates worse
    'nocorrection': [],
    # the default bias correction model
    'smoothlyvaryingbias': [],
    # a country lands if if there's not enough data for more than
    # a simple average, or if the smoothing model identifies a trend
    # in bias that would substantially grow the bias correction over the
    # extrapolation period for which we have no benchmark
    'simpleaveragebias': [],
    'factorsmoothlocf': [
      'AT', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK',
      'EE', 'ES', 'FI', 'GB-SCT', 'HU', 'HR', 'IT', 'JP', 'LT',
      'LU', 'LV', 'NL', 'NO', 'PL', 'PT', 'SE', 'SI', 'SK', 'TW', 'IS',
      'GR', 'CL', 'GB-EAW', 'US', 'FR', 'GB-NIR', 'IL'
    ]
  }
showinoutput: [
      'AT',
      #'AU', only 5 age groups
      'BE',
      'BG',
      #'CA', only 4 age groups
      'CH',
      'CL',
      'CZ',
      'DE',
      'DK',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB-EAW',
      'GB-NIR',
      'GB-SCT',
      'GR',
      'HR',
      'HU',
      'IL',
      'IS',
      'IT',
      'JP',
      #'KR',# only 5 age groups
      'LT',
      'LU',
      'LV',
      'NL',
      'NO',
      #'NZ',# only 3 age groups
      'PL',
      'PT',
      #'RU',# no data past 2021
      'SE',
      'SI',
      'SK',
      'TW',
      'US',
]
excludefromagedecomposition: [
  'GB-SCT', # unreliable youth mortality
  'CL' # unreliable old age mortality
]
# forecast specs
forecast:
  jumpoff: 2020
  h: 5
# figure specifications
figspec:
  dimensions: { width: 180 }
  colors:
    sex: { 'Male': '#004b87', 'Female': '#c60c30' }
credentials:
  # hmd credentials (be careful not to commit)
  hmd_usr: ''
  hmd_pwd: ''
  # hfd credentials (be careful not to commit)
  hfd_usr: ''
  hfd_pwd: ''
# number of simulations
nsim: 250
