# Global constants
skeleton:
  year: { start: 2000, end: 2024 }
  age: { start: 0, end: 100 }
  sex: { Male: 'Male', Female: 'Female' }
  regions: [
      'AT',
      #'AU', only 5 age groups
      'BE',
      'BG',
      #'CA', only 4 age groups
      'CH',
      'CL',
      'CZ',
      'DE',
      'DK',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB-EAW',
      'GB-NIR',
      'GB-SCT',
      'GR',
      'HR',
      'HU',
      'IL', # only 8 age groups
      'IS',
      'IT',
      'JP',
      #'KR', only 5 age groups
      'LT',
      'LU',
      'LV',
      'NL',
      'NO',
      #'NZ', only 3 age groups
      'PL',
      'PT',
      #'RU',
      'SE',
      'SI',
      'SK',
      'TW',
      'US',
    ]
groups:
  {
    'A First wave peak': ['BE', 'GB-EAW', 'IT', 'SI', 'ES', 'SE', 'CH', 'LU', 'GB-SCT'],
    'B Second wave peak': ['BG', 'HR', 'CZ', 'EE', 'GR', 'HU', 'LV', 'LT', 'PL', 'SK', 'US', 'CL'],
    'C Late peak': ['DK', 'FI', 'IS', 'DE', 'NO', 'TW', 'JP'],
    'D Prolonged depression': ['AT', 'FR', 'IL', 'NL', 'GB-NIR', 'PT']
  }
# select exposures to use by default for each country
exposureselection:
  {
    'hmd': ['AT', 'CL', 'GB-EAW', 'GB-NIR', 'GB-SCT', 'HR', 'JP', 'TW', 'US'],
    'wpp24': ['BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HU', 'IL', 'IS', 'IT', 'LT', 'LU', 'LV', 'NL', 'NO', 'PL', 'PT', 'SE', 'SI', 'SK'],
    'wpp22': []
  }
# select countries for which to use rate bias correction model
ratebiascorrection:
  {
    # for cases where correction makes estimates worse
    'nocorrection': ['IS'],
    # the default bias correction model
    'smoothlyvaryingbias': [
      'AT', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK',
      'EE', 'ES', 'FI', 'GB-SCT', 'HU', 'HR', 'IT', 'JP', 'LT',
      'LU', 'NL', 'NO', 'PL', 'PT', 'SE', 'SI', 'SK', 'TW',
    ],
    # a country lands if if there's not enough data for more than
    # a simple average, or if the smoothing model identifies a trend
    # in bias that would substantially grow the bias correction over the
    # extrapolation period for which we have no benchmark
    'simpleaveragebias': [
      'CL',
      'GB-NIR',
      'GR',
      'IL', # data only up to 2017; thus avoid extrapolating a trended bias
      'LV'  # data only up to 2020; thus avoid extrapolating a trended bias
    ],
    # this is a model we use if there is a clear breakpoint in bias in
    # a given year
    'breakpoint2020': ['GB-EAW', 'US'],
    'breakpoint2021': ['FR'],
  }
showinoutput: [
      'AT',
      #'AU', only 5 age groups
      'BE',
      'BG',
      #'CA', only 4 age groups
      'CH',
      'CL', #biased e0 estimates
      'CZ',
      'DE',
      'DK',
      'EE',
      'ES',
      'FI',
      'FR',
      'GB-EAW',
      'GB-NIR',# biased e0 estimates
      'GB-SCT',
      'GR',# biased e0 estimates
      'HR',
      'HU',
      'IL', # only 8 age groups; biased e0 estiamtes
      'IS', #biased e0 estimates
      'IT',
      'JP',
      #'KR',# only 5 age groups
      'LT',
      'LU',
      'LV',
      'NL',
      'NO',
      #'NZ',# only 3 age groups
      'PL',
      'PT',
      #'RU',
      'SE',
      'SI',
      'SK',
      'TW',
      'US',
]
excludefromagedecomposition: [
  'GB-SCT' # unreliable youth mortality
]
# forecast specs
forecast:
  jumpoff: 2020
  h: 5
# figure specifications
figspec:
  dimensions: { width: 180 }
  colors:
    sex: { 'Male': '#004b87', 'Female': '#c60c30' }
credentials:
  # hmd credentials (be careful not to commit)
  hmd_usr: ''
  hmd_pwd: ''
  # hfd credentials (be careful not to commit)
  hfd_usr: ''
  hfd_pwd: ''
# number of simulations
nsim: 250
